name: Build Debian Package

on:
  push:
    branches: [ branchAutoPackage ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential devscripts debhelper fakeroot

    - name: Build Debian package
      run: |
        dpkg-buildpackage -us -uc

    - name: Upload Debian package
      uses: actions/upload-artifact@v3
      with:
        name: devops-deb
        path: ../devops_1.0-1_amd64.deb
