name: Build Debian Package

on:
  push:
    branches: [branchAutoPackage]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential devscripts debhelper

      - name: Build Package
        run: |
          dpkg-buildpackage -us -uc

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: devops-deb
          path: ../devops_1.0-1_amd64.deb
